artifacts_root : artifacts


data_ingestion:
  root_dir : artifacts/data_ingestion
  source_URL : https://github.com/sahilgoregaonkar/Branching-tutorial/raw/main/winequalityN.zip
  local_data_file : artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion